/**
 * Created by johnuiterwyk on 3/12/16.
 */
if (typeof JetLag == "undefined") {
    var JetLag = {};
};
JetLag.Constants =
{
    PLAN_START_3_DAYS_ADVANCE: "PLAN_START_3_DAYS_ADVANCE",
    PLAN_START_DEPARTURE: "PLAN_START_DEPARTURE",
    PLAN_START_ARRIVAL:"PLAN_START_ARRIVAL",
    SHIFT_SPEED_GRADUAL:"SHIFT_SPEED_GRADUAL",
    SHIFT_SPEED_IMMEDIATE:"SHIFT_SPEED_IMMEDIATE",
    PHASE_ADVANCE:"PHASE_ADVANCE",
    PHASE_DELAY:"PHASE_DELAY",
    EVENT_TYPE_FLIGHT:"Flight",
    EVENT_TYPE_SLEEP:"Sleep",
    EVENT_TYPE_WAKE:"Wake",
    EVENT_TYPE_MBT:"mbt",
    EVENT_TYPE_LIGHT:"Seek Light",
    EVENT_TYPE_DARK:"Seek Dark",
}